export default class ActionType {
  static LOGOUT = "LOGOUT";

  static SIGNIN = "SIGNIN";
  static SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
  static SIGNIN_FAIL = "SIGNIN_FAIL";

  // !! Category Action !!
  static GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
  static GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
  static GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL";

  static GET_CATEGORY = "GET_CATEGORY";
  static GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
  static GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

  static CATEGORY_ADD = "CATEGORY_ADD";
  static CATEGORY_ADD_SUCCESS = "CATEGORY_ADD_SUCCESS";
  static CATEGORY_ADD_FAIL = "CATEGORY_ADD_FAIL";

  static CATEGORY_UPDATE = "CATEGORY_UPDATE";
  static CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
  static CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";

  static CATEGORY_DELETE = "CATEGORY_DELETE";
  static CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
  static CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";
  // !! Category Action !!
  static GET_ALL_USERS = "GET_ALL_USERS";
  static GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
  static GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

  static GET_ALL_PROVIDERS = "GET_ALL_PROVIDERS";
  static GET_ALL_PROVIDERS_SUCCESS = "GET_ALL_PROVIDERS_SUCCESS";
  static GET_ALL_PROVIDERS_FAIL = "GET_ALL_PROVIDERS_FAIL";

  static GET_ALL_AVAILIBILITY_REMINDER = "GET_ALL_AVAILIBILITY_REMINDER";
  static GET_ALL_AVAILIBILITY_REMINDER_SUCCESS =
    "GET_ALL_AVAILIBILITY_REMINDER_SUCCESS";
  static GET_ALL_AVAILIBILITY_REMINDER_FAIL =
    "GET_ALL_AVAILIBILITY_REMINDER_FAIL";

  static GET_USER = "GET_USER";
  static GET_USER_SUCCESS = "GET_USER_SUCCESS";
  static GET_USER_FAIL = "GET_USER_FAIL";

  static USER_ADD = "USER_ADD";
  static USER_ADD_SUCCESS = "USER_ADD_SUCCESS";
  static USER_ADD_FAIL = "USER_ADD_FAIL";

  static USER_UPDATE = "USER_UPDATE";
  static USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
  static USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

  static USER_DELETE = "USER_DELETE";
  static USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
  static USER_DELETE_FAIL = "USER_DELETE_FAIL";

  // !! Category Action !!
  static GET_ALL_CITIES = "GET_ALL_CITIES";
  static GET_ALL_CITIES_SUCCESS = "GET_ALL_CITIES_SUCCESS";
  static GET_ALL_CITIES_FAIL = "GET_ALL_CITIES_FAIL";

  static GET_CITY = "GET_CITY";
  static GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
  static GET_CITY_FAIL = "GET_CITY_FAIL";

  static CITY_ADD = "CITY_ADD";
  static CITY_ADD_SUCCESS = "CITY_ADD_SUCCESS";
  static CITY_ADD_FAIL = "CITY_ADD_FAIL";

  static CITY_UPDATE = "CITY_UPDATE";
  static CITY_UPDATE_SUCCESS = "CITY_UPDATE_SUCCESS";
  static CITY_UPDATE_FAIL = "CITY_UPDATE_FAIL";

  static CITY_DELETE = "CITY_DELETE";
  static CITY_DELETE_SUCCESS = "CITY_DELETE_SUCCESS";
  static CITY_DELETE_FAIL = "CITY_DELETE_FAIL";

  // !! Category Action !!
  static GET_ALL_COUPONS = "GET_ALL_COUPONS";
  static GET_ALL_COUPONS_SUCCESS = "GET_ALL_COUPONS_SUCCESS";
  static GET_ALL_COUPONS_FAIL = "GET_ALL_COUPONS_FAIL";

  static GET_COUPON = "GET_COUPON";
  static GET_COUPON_SUCCESS = "GET_COUPON_SUCCESS";
  static GET_COUPON_FAIL = "GET_COUPON_FAIL";

  static COUPON_ADD = "COUPON_ADD";
  static COUPON_ADD_SUCCESS = "COUPON_ADD_SUCCESS";
  static COUPON_ADD_FAIL = "COUPON_ADD_FAIL";

  static COUPON_UPDATE = "COUPON_UPDATE";
  static COUPON_UPDATE_SUCCESS = "COUPON_UPDATE_SUCCESS";
  static COUPON_UPDATE_FAIL = "COUPON_UPDATE_FAIL";

  static COUPON_DELETE = "COUPON_DELETE";
  static COUPON_DELETE_SUCCESS = "COUPON_DELETE_SUCCESS";
  static COUPON_DELETE_FAIL = "COUPON_DELETE_FAIL";

  // !! Request Action !!
  static GET_ALL_REQUESTS = "GET_ALL_REQUESTS";
  static GET_ALL_REQUESTS_SUCCESS = "GET_ALL_REQUESTS_SUCCESS";
  static GET_ALL_REQUESTS_FAIL = "GET_ALL_REQUESTS_FAIL";

  static GET_REQUEST = "GET_REQUEST";
  static GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
  static GET_REQUEST_FAIL = "GET_REQUEST_FAIL";

  static REQUEST_ADD = "REQUEST_ADD";
  static REQUEST_ADD_SUCCESS = "REQUEST_ADD_SUCCESS";
  static REQUEST_ADD_FAIL = "REQUEST_ADD_FAIL";

  static REQUEST_UPDATE = "REQUEST_UPDATE";
  static REQUEST_UPDATE_SUCCESS = "REQUEST_UPDATE_SUCCESS";
  static REQUEST_UPDATE_FAIL = "REQUEST_UPDATE_FAIL";

  static REQUEST_DELETE = "REQUEST_DELETE";
  static REQUEST_DELETE_SUCCESS = "REQUEST_DELETE_SUCCESS";
  static REQUEST_DELETE_FAIL = "REQUEST_DELETE_FAIL";

  // !! Experience Action !!
  static GET_ALL_EXPERIENCES = "GET_ALL_EXPERIENCES";
  static GET_ALL_EXPERIENCES_SUCCESS = "GET_ALL_EXPERIENCES_SUCCESS";
  static GET_ALL_EXPERIENCES_FAIL = "GET_ALL_EXPERIENCES_FAIL";

  static GET_EXPERIENCE = "GET_EXPERIENCE";
  static GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS";
  static GET_EXPERIENCE_FAIL = "GET_EXPERIENCE_FAIL";

  static EXPERIENCE_ADD = "EXPERIENCE_ADD";
  static EXPERIENCE_ADD_SUCCESS = "EXPERIENCE_ADD_SUCCESS";
  static EXPERIENCE_ADD_FAIL = "EXPERIENCE_ADD_FAIL";

  static EXPERIENCE_UPDATE = "EXPERIENCE_UPDATE";
  static EXPERIENCE_UPDATE_SUCCESS = "EXPERIENCE_UPDATE_SUCCESS";
  static EXPERIENCE_UPDATE_FAIL = "EXPERIENCE_UPDATE_FAIL";

  static EXPERIENCE_DELETE = "EXPERIENCE_DELETE";
  static EXPERIENCE_DELETE_SUCCESS = "EXPERIENCE_DELETE_SUCCESS";
  static EXPERIENCE_DELETE_FAIL = "EXPERIENCE_DELETE_FAIL";

  // !! Request Action !!

  static GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
  static GET_ALL_REVIEWS_SUCCESS = "GET_ALL_REVIEWS_SUCCESS";
  static GET_ALL_REVIEWS_FAIL = "GET_ALL_REVIEWS_FAIL";

  static GET_REVIEWS = "GET_REVIEWS";
  static GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
  static GET_REVIEWS_FAIL = "GET_REVIEWS_FAIL";

  static REVIEWS_ADD = "REVIEWS_ADD";
  static REVIEWS_ADD_SUCCESS = "REVIEWS_ADD_SUCCESS";
  static REVIEWS_ADD_FAIL = "REVIEWS_ADD_FAIL";

  static REVIEWS_UPDATE = "REVIEWS_UPDATE";
  static REVIEWS_UPDATE_SUCCESS = "REVIEWS_UPDATE_SUCCESS";
  static REVIEWS_UPDATE_FAIL = "REVIEWS_UPDATE_FAIL";

  static REVIEWS_DELETE = "REVIEWS_DELETE";
  static REVIEWS_DELETE_SUCCESS = "REVIEWS_DELETE_SUCCESS";
  static REVIEWS_DELETE_FAIL = "REVIEWS_DELETE_FAIL";
  // !! SESSIONS Action !!

  static GET_ALL_BOOKING = "GET_ALL_BOOKING";
  static GET_ALL_BOOKING_SUCCESS = "GET_ALL_BOOKING_SUCCESS";
  static GET_ALL_BOOKING_FAIL = "GET_ALL_BOOKING_FAIL";

  static GET_BOOKING = "GET_BOOKING";
  static GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
  static GET_BOOKING_FAIL = "GET_BOOKING_FAIL";

  static BOOKING_ADD = "BOOKING_ADD";
  static BOOKING_ADD_SUCCESS = "BOOKING_ADD_SUCCESS";
  static BOOKING_ADD_FAIL = "BOOKING_ADD_FAIL";

  static BOOKING_UPDATE = "BOOKING_UPDATE";
  static BOOKING_UPDATE_SUCCESS = "BOOKING_UPDATE_SUCCESS";
  static BOOKING_UPDATE_FAIL = "BOOKING_UPDATE_FAIL";

  static BOOKING_DELETE = "BOOKING_DELETE";
  static BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS";
  static BOOKING_DELETE_FAIL = "BOOKING_DELETE_FAIL";
  // !! GetAllGroupBooking Action !!

  static GET_ALL_GROUPBOOKING = "GET_ALL_GROUPBOOKING";
  static GET_ALL_GROUPBOOKING_SUCCESS = "GET_ALL_GROUPBOOKING_SUCCESS";
  static GET_ALL_GROUPBOOKING_FAIL = "GET_ALL_GROUPBOOKING_FAIL";

  static GET_GROUPBOOKING = "GET_GROUPBOOKING";
  static GET_GROUPBOOKING_SUCCESS = "GET_GROUPBOOKING_SUCCESS";
  static GET_GROUPBOOKING_FAIL = "GET_GROUPBOOKING_FAIL";

  static GROUPBOOKING_ADD = "GROUPBOOKING_ADD";
  static GROUPBOOKING_ADD_SUCCESS = "GROUPBOOKING_ADD_SUCCESS";
  static GROUPBOOKING_ADD_FAIL = "GROUPBOOKING_ADD_FAIL";

  static GROUPBOOKING_UPDATE = "GROUPBOOKING_UPDATE";
  static GROUPBOOKING_UPDATE_SUCCESS = "GROUPBOOKING_UPDATE_SUCCESS";
  static GROUPBOOKING_UPDATE_FAIL = "GROUPBOOKING_UPDATE_FAIL";

  static GROUPBOOKING_DELETE = "GROUPBOOKING_DELETE";
  static GROUPBOOKING_DELETE_SUCCESS = "GROUPBOOKING_DELETE_SUCCESS";
  static GROUPBOOKING_DELETE_FAIL = "GROUPBOOKING_DELETE_FAIL";

  static GROUPBOOKING_REJECT = "GROUPBOOKING_REJECT";
  static GROUPBOOKING_REJECT_SUCCESS = "GROUPBOOKING_REJECT_SUCCESS";
  static GROUPBOOKING_REJECT_FAIL = "GROUPBOOKING_REJECT_FAIL";

  static GROUPBOOKING_CREATE = "GROUPBOOKING_CREATE";
  static GROUPBOOKING_CREATE_SUCCESS = "GROUPBOOKING_CREATE_SUCCESS";
  static GROUPBOOKING_CREATE_FAIL = "GROUPBOOKING_CREATE_FAIL";

  static GROUPBOOKINGSTATS_CREATE = "GROUPBOOKINGSTATS_CREATE";
  static GROUPBOOKINGSTATS_CREATE_SUCCESS = "GROUPBOOKINGSTATS_CREATE_SUCCESS";
  static GROUPBOOKINGSTATS_CREATE_FAIL = "GROUPBOOKINGSTATS_CREATE_FAIL";

  // !! SESSIONS Action !!

  static GET_ALL_SESSIONS = "GET_ALL_SESSIONS";
  static GET_ALL_SESSIONS_SUCCESS = "GET_ALL_SESSIONS_SUCCESS";
  static GET_ALL_SESSIONS_FAIL = "GET_ALL_SESSIONS_FAIL";

  static GET_SESSIONS = "GET_SESSIONS";
  static GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
  static GET_SESSIONS_FAIL = "GET_SESSIONS_FAIL";

  static SESSIONS_ADD = "SESSIONS_ADD";
  static SESSIONS_ADD_SUCCESS = "SESSIONS_ADD_SUCCESS";
  static SESSIONS_ADD_FAIL = "SESSIONS_ADD_FAIL";

  static SESSIONS_UPDATE = "SESSIONS_UPDATE";
  static SESSIONS_UPDATE_SUCCESS = "SESSIONS_UPDATE_SUCCESS";
  static SESSIONS_UPDATE_FAIL = "SESSIONS_UPDATE_FAIL";

  static SESSIONS_DELETE = "SESSIONS_DELETE";
  static SESSIONS_DELETE_SUCCESS = "SESSIONS_DELETE_SUCCESS";
  static SESSIONS_DELETE_FAIL = "SESSIONS_DELETE_FAIL";
}
